### ISSUE TITLE
Sample with Dagger

### ISSUE THREAD

**Issue by mantas84** [ww-tech/roxie#13]
Could you extend sample with dagger implementation?

**Comment by jshvarts** [comment]
Roxie would not be doing anything special when it comes to Dagger. In the most straightforward case an Activity or Fragment would be injecting a ViewModelFactory which will produce a ViewModel. Here is one of many samples out there https://proandroiddev.com/viewmodel-with-dagger2-architecture-components-2e06f06c9455

**Comment by mantas84** [comment]
Sorry, I got I little be confused before, since sample uses separate ViewModelFactories for each fragment with initial state parameter.
