### ISSUE TITLE
Migrate to Maven Central

### ISSUE THREAD

**Issue by ziem** [ww-tech/roxie#23]
Hello,
`jcenter` is deprecated with the following message:

>'jcenter' is deprecated 
>Builds will no longer be able to resolve artifacts from JCenter after February 1st, 2022 
>JCenter Maven repository is no longer receiving updates: newer library versions may be available elsewhere

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

It would be great to have Roxie on the Maven Central.

**Comment by michaelcarrano** [comment]
Thanks for creating this issue, I am working on migrating to Maven Central.

**Comment by michaelcarrano** [comment]
@ziem there is a v0.5.0 of Roxie publishing to maven central now. 

Let me know if you run into any issues with it but from my testing, everything appears fine.

**Comment by ziem** [comment]
I've just checked and it works as expected. Thanks!
